version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: nest-mtv-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-mtv
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
    driver: bridge